### ISSUE TITLE
Implement Developer Settings/Switch to Test Env in BC Wallet Regression Tests

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-mobile-test-harness#112]
As of build 575 the app pushed to Sauce Labs is set to the Prod environment. The settings/Developer mode is used to switch to Test. Until this is implemented all Credential issuance and Proof test will fail in the nightly regression cycle.

**Comment by amanji** [comment]
Should this be assigned to a developer?

**Comment by nodlesh** [comment]
Nope. I have to update the tests to always switch to TEST env for every test in the Automated regression suite.
