### ISSUE TITLE
Integrate the Allure Reporting Service

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-mobile-test-harness#9]
- Standup an Allure server. Use the Allure Docker Service.
- updating manage script to take an allure option to output to allure
- A script to upload results to allure. 
- Can we download the video of the test and add to allure?

**Comment by NB-MikeRichardson** [comment]
I'll start looking at this today

**Comment by nodlesh** [comment]
This is complete but we still need to officially stand up an allure server once we have tests running in CI.
